/*
 * GuiClient.java
 *
 * Created on 18 avril 2004, 12:28
 */
 
package tp3;
import javax.swing.*;
/**
 *
 * @author  Yann
 */
public class GuiClient extends javax.swing.JFrame {
    
    /** Creates new form GuiClient */
    public GuiClient(Vendeur v,Client c, boolean ajout,GuiVendeur gui) throws ExceptionGuiClient
    {
        if( c == null)
        {
            throw new ExceptionGuiClient("Le client ne peut etre null.");
        }
        
        if(v == null)
        {
            throw new ExceptionGuiClient("Le vendeur ne peut etre null.");
        }
        
        if(gui==null)
        {
            throw new ExceptionGuiClient("L'interface ne peut etre null.");
        }
        this.c = c;
        this.ajout=ajout;
        this.gui=gui;
        this.v=v;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        texteNom = new javax.swing.JTextField();
        Prenom = new javax.swing.JLabel();
        textePrenom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        texteTelephone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        texteAddresse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        texteCommentaire = new javax.swing.JTextField();
        boutonMiseAJour = new javax.swing.JButton();
        boutonQuitter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Nom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 4, 170);
        getContentPane().add(jLabel1, gridBagConstraints);

        texteNom.setText(c.getNom());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.insets = new java.awt.Insets(11, 20, 0, 0);
        getContentPane().add(texteNom, gridBagConstraints);

        Prenom.setText("Prenom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 4, 0);
        getContentPane().add(Prenom, gridBagConstraints);

        textePrenom.setText(c.getPrenom());
        textePrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textePrenomActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        getContentPane().add(textePrenom, gridBagConstraints);

        jLabel2.setText("Telephone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 170);
        getContentPane().add(jLabel2, gridBagConstraints);

        texteTelephone.setText(c.getNumeroTelephone());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 30, 0);
        getContentPane().add(texteTelephone, gridBagConstraints);

        jLabel3.setText("Addresse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 4, 160);
        getContentPane().add(jLabel3, gridBagConstraints);

        texteAddresse.setText(c.getAdresse());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.insets = new java.awt.Insets(14, 20, 0, 0);
        getContentPane().add(texteAddresse, gridBagConstraints);

        texteCommentaire.setText(c.getCommentaire());
        jScrollPane1.setViewportView(texteCommentaire);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 380;
        gridBagConstraints.ipady = 115;
        gridBagConstraints.insets = new java.awt.Insets(13, 4, 5, 9);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        boutonMiseAJour.setText("Mise a jour");
        boutonMiseAJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMiseAJourActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 25, 0);
        getContentPane().add(boutonMiseAJour, gridBagConstraints);

        boutonQuitter.setText("Quitter");
        boutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonQuitterActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.insets = new java.awt.Insets(19, 10, 11, 0);
        getContentPane().add(boutonQuitter, gridBagConstraints);

        jMenu1.setText("Menu");
        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void boutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonQuitterActionPerformed
        // Add your handling code here:
        dispose();
    }//GEN-LAST:event_boutonQuitterActionPerformed

    private void boutonMiseAJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMiseAJourActionPerformed
        // Add your handling code here:
        try
        {
            c.setNom(texteNom.getText());
            c.setPrenom(textePrenom.getText());
            c.setAdresse(texteAddresse.getText());
            c.setNumeroTelephone(texteTelephone.getText());
            c.setCommentaire(texteCommentaire.getText());
            if(ajout)
            {
                Client temp=v.getClient(c.getIdentifiantClient());
                if(temp==null)
                {
                    v.ajoutClient(c);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Le client existe deja", "alert", JOptionPane.ERROR_MESSAGE);         
                }
            }
            gui.refreshListeClient();
            dispose();
        }
        catch(ExceptionPersonne e)
        {
            JOptionPane.showMessageDialog(null, "Impossible de modifier le client:" + e, "alert", JOptionPane.ERROR_MESSAGE); 
        }
        catch(ExceptionClient e)
        {
            JOptionPane.showMessageDialog(null, "Impossible de modifier le client:" + e, "alert", JOptionPane.ERROR_MESSAGE); 
        }
        catch(ExceptionVendeur e)
        {
            JOptionPane.showMessageDialog(null, "Impossible de modifier le client:" + e, "alert", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_boutonMiseAJourActionPerformed

    private void textePrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textePrenomActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_textePrenomActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Prenom;
    private javax.swing.JButton boutonMiseAJour;
    private javax.swing.JButton boutonQuitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField texteAddresse;
    private javax.swing.JTextField texteCommentaire;
    private javax.swing.JTextField texteNom;
    private javax.swing.JTextField textePrenom;
    private javax.swing.JTextField texteTelephone;
    // End of variables declaration//GEN-END:variables
    Client c;
    Vendeur v;
    boolean ajout;
    GuiVendeur gui;
}
