/*
 * GuiPrincipal.java
 *
 * Created on 17 avril 2004, 18:20
 */
 
package tp3;
import javax.swing.*;
/**
 *
 * @author  Yann
 */
public class GuiPrincipal extends javax.swing.JFrame {
    
    /** Creates new form GuiPrincipal */
    public GuiPrincipal() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        codeVendeur = new javax.swing.JTextField();
        boutonConsulter = new javax.swing.JButton();
        boutonQuitter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        boutonExit = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Numero vendeur:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 131, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        codeVendeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeVendeurActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 131, 0);
        getContentPane().add(codeVendeur, gridBagConstraints);

        boutonConsulter.setText("Consulter");
        boutonConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonConsulterActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 9);
        getContentPane().add(boutonConsulter, gridBagConstraints);

        boutonQuitter.setText("Quitter");
        boutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonQuitterActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.insets = new java.awt.Insets(74, 20, 33, 9);
        getContentPane().add(boutonQuitter, gridBagConstraints);

        jMenu1.setText("Menu");
        boutonExit.setText("Quitter");
        boutonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonExitActionPerformed(evt);
            }
        });

        jMenu1.add(boutonExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void boutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonQuitterActionPerformed
        // Add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_boutonQuitterActionPerformed

    private void boutonConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonConsulterActionPerformed
        Vendeur v=app.trouveVendeur(codeVendeur.getText());
        if(v != null)
        {
            try
            {
                new GuiVendeur(v,app).show();
            }
            catch( ExceptionGuiVendeur e)
            {
                JOptionPane.showMessageDialog(null, "Impossible d'afficher la fenetre vendeur: " + e, "alert", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_boutonConsulterActionPerformed

    private void codeVendeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeVendeurActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_codeVendeurActionPerformed

    private void boutonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_boutonExitActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            // Trouve les 3 noms de fichier.
            String fichierAutomobile="";
            String fichierVendeurs="";
            String fichierTransaction="";
            
            if(args.length>=3)
            {
                fichierAutomobile=args[0];
                fichierVendeurs=args[1];
                fichierTransaction=args[2];
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Vous devez specifier trois nom de fichier sur la ligne de commande\n ex.: java application automobile.txt vendeurs.txt transaction.txt", "alert", JOptionPane.ERROR_MESSAGE); 
                return; // Quitte le programme.
            }
        app = new Application(fichierVendeurs,fichierAutomobile,fichierTransaction);
        new GuiPrincipal().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonConsulter;
    private javax.swing.JMenuItem boutonExit;
    private javax.swing.JButton boutonQuitter;
    private javax.swing.JTextField codeVendeur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    static private Application app;

}
