/*
 * JFrame.java
 *
 * Created on 25 avril 2004, 16:29
 */

/**
 * <p>Title: Classe GuiTransaction</p>
 * <p>Description: Classe GUI</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * @author Framcis Goyer (GOYF14037303)
 * @version 1.0
 */
package tp3;

import  java.io.*;
import javax.swing.*;
import java.util.*;

public class GuiTransaction extends javax.swing.JFrame {

    /** Creates new form JFrame
     * @param v Vendeur
     * @param app Application
     * @throws ExceptionGuiVendeur
     */
    public GuiTransaction(Vendeur v, Application app) throws ExceptionGuiVendeur
    {
        if (v==null)
        {
            throw new ExceptionGuiVendeur("Le vendeur ne peut etre null. ");
        }
        else if(app==null){
            throw new ExceptionGuiVendeur("l'app ne pas etre null.");
        }
        this.v=v;
        this.app=app;
        initComponents();
        noVendeur.setText(v.getNumeroEmploye());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel17 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        annee = new javax.swing.JTextField();
        mois = new javax.swing.JTextField();
        jour = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        noSerie = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        btnConfirmer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        btnListe = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        noVendeur = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        clientSelect = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        prenomClient = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        noTelephone = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        prixAuto = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Quitter = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel6.setText("VENDEUR");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 40, 70, 20);

        jLabel14.setFont(new java.awt.Font("MS Sans Serif", 0, 24));
        jLabel14.setText("  Fiche Transaction");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(80, 0, 210, 40);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 59;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel4.setLayout(null);

        jLabel2.setText("Date :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(0, 0, 40, 20);

        jLabel3.setText("Annee :");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(60, 0, 50, 20);

        jLabel4.setText("  Mois :");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(170, 0, 40, 20);

        jLabel5.setText("  Jour :");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(260, 0, 40, 20);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(30, 0, 40, 20);

        annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anneeActionPerformed(evt);
            }
        });

        jPanel4.add(annee);
        annee.setBounds(110, 0, 60, 20);

        mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisActionPerformed(evt);
            }
        });

        jPanel4.add(mois);
        mois.setBounds(212, 0, 50, 20);

        jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourActionPerformed(evt);
            }
        });

        jPanel4.add(jour);
        jour.setBounds(300, 0, 50, 20);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(350, 0, 50, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel13.setLayout(null);

        jLabel8.setText("No. serie  :");
        jPanel13.add(jLabel8);
        jLabel8.setBounds(0, 0, 100, 20);

        jPanel13.add(jPanel14);
        jPanel14.setBounds(290, 0, 120, 20);

        noSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSerieActionPerformed(evt);
            }
        });

        jPanel13.add(noSerie);
        noSerie.setBounds(90, 0, 190, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 409;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel13, gridBagConstraints);

        btnConfirmer.setText("Confimer");
        btnConfirmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmerMouseClicked(evt);
            }
        });

        jPanel16.add(btnConfirmer);

        btnAnnuler.setText("Annuler");
        btnAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnnulerMouseClicked(evt);
            }
        });

        jPanel16.add(btnAnnuler);

        btnListe.setLabel("Liste ");
        btnListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeActionPerformed(evt);
            }
        });

        jPanel16.add(btnListe);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel16, gridBagConstraints);

        jPanel2.setLayout(null);

        jLabel1.setText("No. vendeur :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 80, 20);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(250, 0, 150, 20);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(70, 0, 20, 20);

        noVendeur.setBackground(new java.awt.Color(204, 204, 204));
        noVendeur.setFocusable(false);
        jPanel2.add(noVendeur);
        noVendeur.setBounds(90, 0, 160, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel8.setLayout(null);

        jLabel9.setText("CLIENT");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(0, 20, 60, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 409;
        gridBagConstraints.ipady = 39;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel8, gridBagConstraints);

        jPanel9.setLayout(null);

        clientSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientSelectActionPerformed(evt);
            }
        });

        jPanel9.add(clientSelect);
        clientSelect.setBounds(90, 0, 200, 20);

        jLabel7.setText("Nom :");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(0, 0, 90, 20);

        jPanel9.add(jPanel12);
        jPanel12.setBounds(290, 0, 120, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 409;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel9, gridBagConstraints);

        jPanel10.setLayout(null);

        jLabel10.setText("Prenom :");
        jPanel10.add(jLabel10);
        jLabel10.setBounds(0, 0, 90, 20);

        prenomClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomClientActionPerformed(evt);
            }
        });

        jPanel10.add(prenomClient);
        prenomClient.setBounds(90, 0, 200, 20);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(290, 0, 120, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 409;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel10, gridBagConstraints);

        jPanel18.setLayout(null);

        jLabel11.setText("No. telephone :");
        jPanel18.add(jLabel11);
        jLabel11.setBounds(0, 0, 90, 20);

        noTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelephoneActionPerformed(evt);
            }
        });

        jPanel18.add(noTelephone);
        noTelephone.setBounds(90, 0, 130, 20);

        jPanel18.add(jPanel19);
        jPanel19.setBounds(220, 0, 190, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 409;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel18, gridBagConstraints);

        jPanel20.setLayout(null);

        jLabel12.setText("VOITURE");
        jPanel20.add(jLabel12);
        jLabel12.setBounds(0, 20, 50, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 409;
        gridBagConstraints.ipady = 39;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel20, gridBagConstraints);

        jPanel21.setLayout(null);

        jLabel13.setText("Prix :");
        jPanel21.add(jLabel13);
        jLabel13.setBounds(0, 0, 90, 20);

        jPanel21.add(prixAuto);
        prixAuto.setBounds(90, 0, 90, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 409;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel21, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel22, gridBagConstraints);

        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        Quitter.setActionCommand("Quitter");
        Quitter.setLabel("Quitter");
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });

        menu.add(Quitter);

        jMenuBar2.add(menu);

        setJMenuBar(jMenuBar2);

        pack();
    }//GEN-END:initComponents

    private void btnListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeActionPerformed
        // TODO add your handling code here:
        try
        {
            new GuiListeTransaction(app).show();
        }
        catch(ExceptionGuiListe e)
        {
            JOptionPane.showMessageDialog(null, "Impossible d'obtenir la liste des transactions:" + e, "alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListeActionPerformed

    private void jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jourActionPerformed

    private void moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moisActionPerformed

    private void anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anneeActionPerformed

    private void noSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noSerieActionPerformed

    private void noTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelephoneActionPerformed

    private void prenomClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomClientActionPerformed

    private void clientSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientSelectActionPerformed

    private void btnAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnulerMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnAnnulerMouseClicked

    private void btnConfirmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmerMouseClicked

            try
            {
                Automobile auto = app.trouveAutomobile(noSerie.getText());
                Client client=v.getClient(clientSelect.getText()+noTelephone.getText());
                if (auto == null)
                {
                    JOptionPane.showMessageDialog(null, "Vous devez selectionner un numéro de série valide.");
                }
                else
                {
                    if (!auto.getVendue()) //l'auto vendue
                    {
                        JOptionPane.showMessageDialog(null, "Cette voiture a deja etee vendue.");
                        noSerie.setText("");//refraichir la case de l'element erronne
                    }
                    else if(auto.getPrixCoutant() > Integer.parseInt(prixAuto.getText()))
                    {   //prix d'acaht doit etre sup. au prix coutant
                        JOptionPane.showMessageDialog(null, "Le prix d'achat doit etre superieur a "+auto.getPrixCoutant()+"$ .");
                        prixAuto.setText("");//refraichir la case de l'element erronne
                    }
                    else if(client == null)
                    {
                        JOptionPane.showMessageDialog(null, "Le client selectionne ne fait pas partie de la liste des clients du venduer #"+noVendeur.getText()+" .");
                        clientSelect.setText("");//refraichir la case de l'element erronne
                        prenomClient.setText("");
                        noTelephone.setText("");
                    }
                else
                {
                  try
                  {
                      GregorianCalendar date = new GregorianCalendar(Integer.parseInt(annee.getText()),Integer.parseInt(mois.getText())-1,Integer.parseInt(jour.getText()));

                        try
                        {
                            Transaction tr = new Transaction(date, Integer.parseInt(prixAuto.getText()),noVendeur.getText(),(clientSelect.getText() + noTelephone.getText()),noSerie.getText());
                            JOptionPane.showMessageDialog(null, "transaction ajoutee par"+ noVendeur.getText() );
                            auto.setVendue(true);
                            Set transactions= app.getListeTransaction();
                            transactions.add(tr);
                        }
                        catch (ExceptionTransaction e)
                        {
                            JOptionPane.showMessageDialog(null, "Impossible de creer la transaction:" + e, "alert", JOptionPane.ERROR_MESSAGE);
                        }
                    }

                catch(NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "La date que vous tentez d'entrer est invalide." + e,"alert", JOptionPane.ERROR_MESSAGE);
                }
             }
           }
        }
        catch (ExceptionVendeur e)
        {
            JOptionPane.showMessageDialog(null, "Impossible de creer la transaction:" + e, "alert", JOptionPane.ERROR_MESSAGE);
        }
        dispose();

    }//GEN-LAST:event_btnConfirmerMouseClicked

    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_QuitterActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    /* Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       dispose();
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Quitter;
    private javax.swing.JTextField annee;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnConfirmer;
    private javax.swing.JButton btnListe;
    private javax.swing.JTextField clientSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jour;
    private javax.swing.JMenu menu;
    private javax.swing.JTextField mois;
    private javax.swing.JTextField noSerie;
    private javax.swing.JTextField noTelephone;
    private javax.swing.JTextField noVendeur;
    private javax.swing.JTextField prenomClient;
    private javax.swing.JTextField prixAuto;
    // End of variables declaration//GEN-END:variables
    static private Application app;
    Vendeur v;

}
