/*
 * GuiVendeur.java
 *
 * Created on 17 avril 2004, 18:49
 */

package tp3;

// package tp3;
import  java.io.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author  Yann
 */
public class GuiVendeur extends javax.swing.JFrame {
    
    /** Creates new form GuiVendeur */
    public GuiVendeur(Vendeur v, Application app) throws ExceptionGuiVendeur
    {
        if(v==null)
        {
            throw new ExceptionGuiVendeur("le vendeur ne peut etre null.");
        }
        /*else if(app==null){
            throw new ExceptionGuiVendeur("l'app ne pas etre null.");
        }*/
        this.v=v;
        this.app=app;
        initComponents();
        texteCodeVendeur.setText(v.getNumeroEmploye());
        texteNom.setText(v.getNom());
        textePrenom.setText(v.getPrenom());
    }
    
    public void refreshListeClient()
    {
            Vector v = new Vector(10,5);
            Set clients=this.v.getListeClient();
            Iterator iter = clients.iterator();
            
            while(iter.hasNext())
            {
                Client client=(Client) iter.next();
                if(client != null)
                {
                    v.add(client);
                }
            }
            
            listeClient.setListData(v);        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texteCodeVendeur = new javax.swing.JTextField();
        texteNom = new javax.swing.JTextField();
        textePrenom = new javax.swing.JTextField();
        boutonAJour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeClient = new javax.swing.JList();
        boutonAjout = new javax.swing.JButton();
        boutonQuitter = new javax.swing.JButton();
        boutonTransaction = new javax.swing.JButton();
        boutonInventaire = new javax.swing.JButton();
        boutonCommision = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Transaction = new javax.swing.JMenuItem();
        menuInventaire = new javax.swing.JMenuItem();
        menuCommission = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setBackground(new java.awt.Color(102, 255, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Code vendeur:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("nom:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("prenom:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 4, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        texteCodeVendeur.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 30, 0);
        getContentPane().add(texteCodeVendeur, gridBagConstraints);

        texteNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteNomActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        getContentPane().add(texteNom, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(textePrenom, gridBagConstraints);

        boutonAJour.setText("Mise a jour");
        boutonAJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAJourActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 24, 0);
        getContentPane().add(boutonAJour, gridBagConstraints);

        listeClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        Set clients=v.getListeClient();
        Iterator iter = clients.iterator();
        Vector v=new Vector(10,5);
        while(iter.hasNext())
        {
            Client client=(Client) iter.next();
            if(client != null)
            {
                v.add(client);
            }
        }
        listeClient.setListData(v);
        listeClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeClientMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(listeClient);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 181;
        gridBagConstraints.ipady = -21;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 1, 11);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        boutonAjout.setText("Ajout Client");
        boutonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.insets = new java.awt.Insets(14, 30, 24, 0);
        getContentPane().add(boutonAjout, gridBagConstraints);

        boutonQuitter.setText("Quitter");
        boutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonQuitterActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 87;
        gridBagConstraints.insets = new java.awt.Insets(4, 30, 0, 0);
        getContentPane().add(boutonQuitter, gridBagConstraints);

        boutonTransaction.setText("Transaction");
        boutonTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonTransactionActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 30, 0);
        getContentPane().add(boutonTransaction, gridBagConstraints);

        boutonInventaire.setText("Inventaire");
        boutonInventaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonInventaireActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
        getContentPane().add(boutonInventaire, gridBagConstraints);

        boutonCommision.setText("Commision");
        boutonCommision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCommisionActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.insets = new java.awt.Insets(4, 30, 0, 0);
        getContentPane().add(boutonCommision, gridBagConstraints);

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Transaction.setLabel("Transaction");
        Transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionActionPerformed(evt);
            }
        });

        jMenu1.add(Transaction);

        menuInventaire.setLabel("Inventaire");
        menuInventaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInventaireActionPerformed(evt);
            }
        });

        jMenu1.add(menuInventaire);

        menuCommission.setLabel("Calculer Commision");
        menuCommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCommissionActionPerformed(evt);
            }
        });

        jMenu1.add(menuCommission);

        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void boutonCommisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCommisionActionPerformed
        // Add your handling code here:
        try {
           new GuiCommission(v,app).show();
         }
         catch (ExceptionGuiVendeur e)
         {
             JOptionPane.showMessageDialog(null, "Le Vendeur ne peut pas etre nul. " + e, "alert", JOptionPane.ERROR_MESSAGE);         
         }
        
    }//GEN-LAST:event_boutonCommisionActionPerformed

    private void boutonInventaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonInventaireActionPerformed
         try{
            new GuiInventaire(app).show();
        }
        catch (ExceptionGuiInventaire e){
            JOptionPane.showMessageDialog(null, "Impossible de faire l'inventaire. " + e, "alert", JOptionPane.ERROR_MESSAGE);         

        }        
    }//GEN-LAST:event_boutonInventaireActionPerformed

    private void boutonTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonTransactionActionPerformed
       try{
            new GuiTransaction(v,app).show();
        }
        catch (ExceptionGuiVendeur e)
        {
            JOptionPane.showMessageDialog(null, "Impossible de faire une transaction:" + e, "alert", JOptionPane.ERROR_MESSAGE);         
        }
    }//GEN-LAST:event_boutonTransactionActionPerformed

    private void menuCommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCommissionActionPerformed
        // TODO add your handling code here:
        try {
           new GuiCommission(v,app).show();
         }
         catch (ExceptionGuiVendeur e)
         {
             JOptionPane.showMessageDialog(null, "Le Vendeur ne peut pas etre nul. " + e, "alert", JOptionPane.ERROR_MESSAGE);         
         }
         
    }//GEN-LAST:event_menuCommissionActionPerformed

    private void menuInventaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInventaireActionPerformed
        // TODO add your handling code here:
        try{
            new GuiInventaire(app).show();
        }
        catch (ExceptionGuiInventaire e){
            JOptionPane.showMessageDialog(null, "Impossible de faire l'inventaire. " + e, "alert", JOptionPane.ERROR_MESSAGE);         

        }
    }//GEN-LAST:event_menuInventaireActionPerformed

    private void TransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionActionPerformed
        // TODO add your handling code here:
        try{
            new GuiTransaction(v,app).show();
        }
        catch (ExceptionGuiVendeur e)
        {
            JOptionPane.showMessageDialog(null, "Impossible de faire une transaction:" + e, "alert", JOptionPane.ERROR_MESSAGE);         
        }
    }//GEN-LAST:event_TransactionActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void texteNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteNomActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_texteNomActionPerformed

    private void boutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonQuitterActionPerformed
        // Add your handling code here:
        dispose();
    }//GEN-LAST:event_boutonQuitterActionPerformed

    private void boutonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutActionPerformed
        // Add your handling code here:
        try
        {
            Client c = new Client ("","","","","");
            new GuiClient(v,c,true,this).show();
            
        }
        catch (ExceptionClient e)
        {
            JOptionPane.showMessageDialog(null, "Impossible d'ajouter le client:" + e, "alert", JOptionPane.ERROR_MESSAGE); 
        }
        catch (ExceptionPersonne e)
        {
            JOptionPane.showMessageDialog(null, "Impossible d'ajouter le client:" + e, "alert", JOptionPane.ERROR_MESSAGE); 
        }
        catch (ExceptionGuiClient e)
        {
            JOptionPane.showMessageDialog(null, "Impossible d'ajouter le client:" + e, "alert", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_boutonAjoutActionPerformed

    private void listeClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeClientMouseClicked
        // Add your handling code here:
        try
        {
            Client c = (Client) listeClient.getSelectedValue();
            if( c != null)
            {
                new GuiClient(v,c,false,this).show();
    
            }
        }
        catch (ExceptionGuiClient e)
        {
            JOptionPane.showMessageDialog(null, "Impossible de creer la fenetre client:" + e, "alert", JOptionPane.ERROR_MESSAGE); 
        }

    }//GEN-LAST:event_listeClientMouseClicked

    private void boutonAJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAJourActionPerformed
        // Add your handling code here:
        try
        {
           v.setNom(texteNom.getText());
           v.setPrenom(textePrenom.getText());
        }
        catch(ExceptionPersonne e)
        {
            JOptionPane.showMessageDialog(null, "Impossible de modifier le vendeur:" + e, "alert", JOptionPane.ERROR_MESSAGE); 

        }
    }//GEN-LAST:event_boutonAJourActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Transaction;
    private javax.swing.JButton boutonAJour;
    private javax.swing.JButton boutonAjout;
    private javax.swing.JButton boutonCommision;
    private javax.swing.JButton boutonInventaire;
    private javax.swing.JButton boutonQuitter;
    private javax.swing.JButton boutonTransaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listeClient;
    private javax.swing.JMenuItem menuCommission;
    private javax.swing.JMenuItem menuInventaire;
    private javax.swing.JTextField texteCodeVendeur;
    private javax.swing.JTextField texteNom;
    private javax.swing.JTextField textePrenom;
    // End of variables declaration//GEN-END:variables
    private Vendeur v;
    private  static Application app;

}
