CFLAGS_REL=  /nologo  /MD /W3 /GX  /ox /GA /G6  /GF  -c	 
CC=cl.exe
OBJS_RELEASE= tp3.obj   
HEADER= 

LIBS=  kernel32.lib odbccp32.lib comctl32.lib rpcrt4.lib 

tp3.exe: $(OBJS_RELEASE) makefile 
	link  /nologo /machine:I386 /MAP /subsystem:console  -out:tp3.exe $(OBJS_RELEASE)  $(LIBS) /OPT:NOWIN98 /INCREMENTAL:NO 

tp3.obj:  tp3.c $(HEADER)
	$(CC)  $(CFLAGS_REL) tp3.c 

