drop table commandes;
drop table articlepret; 
drop table articlereservation;
drop table clients; 
drop table articles;


CREATE TABLE ARTICLES(
   NUMARTICLE NUMBER,
   NOM VARCHAR(20),
   PRIXUNITAIRE INT,
   QTEDISPONIBLE NUMBER,
   CONSTRAINT CLEP_ARTICLES PRIMARY KEY(NUMARTICLE));

CREATE TABLE CLIENTS(
   NUMCLIENT NUMBER,
   NOM VARCHAR(30),
   MOTPASSE VARCHAR(10),
   TELEPHONE CHAR(15),
   COURRIEL VARCHAR(40) unique,
   COULEUR NUMBER,
   CONSTRAINT CLEP_CLIENT PRIMARY KEY(NUMCLIENT));

CREATE TABLE ARTICLEPRET(
   NUMCLIENT NUMBER,
   NUMARTICLE NUMBER,
   DATEDEBUT DATE,
   DATEFIN DATE,
   CONSTRAINT CLEP_ARTICLEPRET PRIMARY KEY(NUMCLIENT,NUMARTICLE,DATEDEBUT,DATEFIN),
   CONSTRAINT CLEE_NUMCLIENT FOREIGN KEY (NUMCLIENT) REFERENCES CLIENTS,
   CONSTRAINT CLEE_NUMARTICLE FOREIGN KEY (NUMARTICLE) REFERENCES ARTICLES);

CREATE TABLE COMMANDES(
   NUMCLIENT NUMBER,
   NUMARTICLE NUMBER,
   DATEETHEURE DATE,
   QUANTITE NUMBER,
   CONSTRAINT CLEP_COMMANDE PRIMARY KEY (NUMCLIENT,NUMARTICLE,DATEETHEURE),
   CONSTRAINT CLEE_CLIENT_COM FOREIGN KEY (NUMCLIENT) REFERENCES CLIENTs,
   CONSTRAINT CLEE_NUMARTICLE_COM FOREIGN KEY (NUMARTICLE) REFERENCES ARTICLES);

CREATE TABLE ARTICLERESERVATION(
	NUMCLIENT NUMBER,
        NUMARTICLE NUMBER,
	POSITION NUMBER,
	CONSTRAINT CLEP_ARTICLERESERVATION PRIMARY KEY(NUMCLIENT,NUMARTICLE,POSITION),
   	CONSTRAINT CLEE_NUMCLIENT_RES FOREIGN KEY (NUMCLIENT) REFERENCES CLIENTS,
   	CONSTRAINT CLEE_NUMARTICLE_RES FOREIGN KEY (NUMARTICLE) REFERENCES ARTICLES
);
